### ISSUE TITLE
Mejoras 

### ISSUE THREAD

**Issue by MRocioRR** [MRocioRR/GymkoFit#2]
- Modificar de bd a csv "usuarios_app" o "usuarios" estos serán los añadidos nuevos o leídos desde csv. Contemplar ambas posibilidades.
- Resumir si se puede las líneas de código y revisar si sobran algunas (he realizados muchos cambios por errores).
- Podemos meter colores.
- El logo en está última versión no se mostraba correcto (revisamos).
- Podemos meter el cálculo de la primera app (calculadora).
- Incluir texto explicativo ( no más de 4 o 5 líneas).
- Queda pendiente si se borran los registros.
-  Incluir si se puede autocompletar un registro poniendo id (para no tener que estás señalando todo cuando se use para meter el peso).

**Comment by MRocioRR** [comment]
![image](https://github.com/MRocioRR/GymkoFit/assets/52194835/b3700c92-3044-4008-91a8-70e760ddc25a)

**Comment by lockedofh** [comment]
Resolved.
